image: newsdev/go:1.2

services:
  - redis

env:
  - AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}
  - AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}

script:
  - ln -s `pwd` $GOPATH/src/github.com/buth/stocker
  - go get -d -v ./...
  - go test -v ./...
  - ./release.sh

notify:
  email:
    recipients:
      - eric.buth@nytimes.com
